spring:
  redis:
    host: 127.0.0.1
    port: 6379
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javainterview?characterEncoding=utf-8&useSSL=false
    username: root
    password: 351848327
  mail:
    host: smtp.qq.com
    username: 351848327@qq.com
    password: mqfjizobifrnbjcb